language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      script:
        - ./autogen.sh
        - ./build-windows-binaries.sh
        - ./build-windows-package.sh
    - os: linux
      script:
        - ./autogen.sh
        - ./build-linux-binaries.sh
    - os: linux
      script:
        - ./autogen.sh
        - ./build-linux-package.sh -us -uc
    - os: osx
      script:
        - ./autogen.sh
        - ./build-mac-binaries.sh

addons:
  apt:
    packages:
      # For Debian packaging
      - devscripts
      - fakeroot
      - build-essential
      - debhelper
      - cdbs
      # For cross-compiling Windows executables
      - mingw-w64
      - gcc-mingw-w64-i686
      - g++-mingw-w64-i686
      - gcc-mingw-w64-x86-64
      - g++-mingw-w64-x86-64
